# Generated by Django 6.0.7 on 2026-09-09 15:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('doc_type', models.CharField(blank=True, choices=[('invoice', 'Invoice'), ('shipping', 'Shipping'), ('receipt', 'Receipt'), ('other', 'Other')], db_index=True, max_length=20, null=True)),
                ('langue', models.CharField(blank=True, choices=[('fr', 'Français'), ('en', 'English'), ('ar', 'العربية'), ('autre', 'Autre')], max_length=10, null=True)),
                ('fournisseur', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('numero', models.CharField(blank=True, max_length=100, null=True)),
                ('montant_ttc', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('field_confidence', models.JSONField(blank=True, null=True)),
                ('needs_review', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='SpreadsheetImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='spreadsheets/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('mapped', 'Mapped'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('data_type', models.CharField(blank=True, max_length=50, null=True)),
                ('column_mapping', models.JSONField(blank=True, null=True)),
                ('sample_rows', models.JSONField(blank=True, null=True)),
                ('normalized_rows', models.JSONField(blank=True, null=True)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('needs_review', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spreadsheet_imports', to='api.organization')),
            ],
        ),
    ]
