# Generated by Django 6.0.7 on 2026-09-10 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_multi_tenant_setup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='organization',
            new_name='organisation',
        ),
    ]
