# Generated by Django 6.0.7 on 2026-09-10 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_organization_role_organisation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='organization',
            new_name='organisation',
        ),
    ]
